import Head from "next/head";

import Picker from "./Picker";
import styles from "./index.module.css";
import { options } from "./state";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Picker options={options} />
        </div>
      </main>
    </>
  );
}
